esphome:
  name: espnow

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

esp_now:
  channel: 3
  espnow_interface: "STA"
  compat_mode: True
  on_message:
    - address: "AA:BB:CC:DD:EE:FF"
      espnow_rssi: -60
      then:
        - logger.log: "Hello World"
# wifi:
#  ssid: "qwertyuii"
#  password: "123456789"
