esphome:
  name: espnow

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

esp_now:
  id: espnow
  channel: 3
  espnow_interface: "STA"
  compat_mode: True
  on_message:
    - address: "AA:BB:CC:DD:EE:FF"
      espnow_rssi: -60
      then:
        - logger.log: "Hello World"
# wifi:
#  ssid: "qwertyuii"
#  password: "123456789"

script:
  - id: send_message
    mode:
      restart # Light will be kept on during 1 minute since
      # the latest time the script is executed
    then:
      - esp_now.send:
          address: "aa:aa:aa:aa:aa:aa"
          payload: "hello world"
      - delay: 1 min
