esphome:
  name: espnow

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

esp_now:
  channel: 3
  espnow_interface: "STA"
#wifi:
#  ssid: "qwertyuii"
#  password: "123456789"
